### ISSUE TITLE
Sidebar navigation takes over half the width of the page when Indigo theme is used

### ISSUE THREAD

**Issue by crathbun428** [openedx/frontend-app-learning#1401]
**Steps to Reproduce**
1. Login to an instance using the Indigo theme as an admin user to ensure the courseware.enable_navigation_sidebar waffle flag is enabled
2. Navigate to an in-course experience page 
3. With the sidebar navigation expanded, view the page

**Expected Behavior**
1. The sidebar navigation when expanded takes up much less than half of the page horizontally (see attached image from an in-course experience page using the Open edX theme)
2. There is a reasonable amount of blank space on either side of the course content/sidebar content
![Screenshot 2024-05-31 at 4 00 48 PM](https://github.com/openedx/frontend-app-learning/assets/57507106/7f735c41-7782-4cea-828a-8ad281376f42)

**Expected Behavior**
1. The sidebar navigation when expanded takes up half of the page horizontally (see attached image from an in-course experience page using the Indigo theme)
2. There is a lot of extra blank space on either side of the course content/sidebar content
![Screenshot 2024-05-31 at 3 58 51 PM](https://github.com/openedx/frontend-app-learning/assets/57507106/80a7c34f-62d7-4434-9df0-4121baad0b92)

**Comment by mariajgrimaldi** [comment]
FYI @arbrandes @brian-smith-tcril @openedx/2u-infinity, please tag anyone you think can help. Thanks!

**Comment by crathbun428** [comment]
@GlugovGrGlib - curious about the effort level for this fix? The experience navigating course content in indigo is more clunky with the course content view so narrow (see screenshot above). It's not a release blocker, and because this isn't the default experience, I didn't mark it as high priority, but resolving this ahead of release (if possible) would be a huge win for this feature (I'd prioritize it second in the sidebar bugs - below #1013).

**Comment by crathbun428** [comment]
@brian-smith-tcril - Curious if it's possible to easily tell if this is a quick and simple fix or maybe something deeper?

**Comment by brian-smith-tcril** [comment]
Considering this is an issue on the indigo theme and not on the Open edX theme, it would need to be addressed there.

Since this is in an MFE, it would need to be addressed in the indigo fork of `@openedx/brand`.

The `tutor-indigo` plugin installs `@edly-io/indigo-brand-openedx` pinned to version `^1.0.0` (see https://github.com/overhangio/tutor-indigo/blob/57ffd11cfc55e4640b224a1f3826a7e9717b8f5f/tutorindigo/plugin.py#L108), meaning the latest `1.x.x` release.

As of writing, that is version `1.4.1` (https://www.npmjs.com/package/@edly-io/indigo-brand-openedx/v/1.4.1?activeTab=versions)

This appears to have been published from the `quince/indigo` branch, as https://github.com/edly-io/brand-openedx/releases/tag/indigo-1.4.1 is on commit `0622d6a`, and as of writing that matches the latest commit here https://github.com/edly-io/brand-openedx/tree/quince/indigo

The issue appears to be this line https://github.com/edly-io/brand-openedx/blob/0622d6a6bdf1f5ba84bfaf6cd4d18133a4b3b57d/paragon/_overrides.scss#L14

```scss
.container-xl {
    max-width: 1090px !important;
```

With that removed I see

![image](https://github.com/openedx/frontend-app-learning/assets/112954497/ae9f0369-0269-471f-afbb-2383ced3f189)

However, simply removing that line will change a lot of things globally. I don't expect that change to be something indigo maintainers would be happy with, and I'm not sure what it would take to address this in a less far-reaching way.

**Comment by crathbun428** [comment]
@brian-smith-tcril - Thanks for this insight, Brian. Not excited about the result, but this input will help me make some calls. Thank you!

**Comment by GlugovGrGlib** [comment]
Hi @crathbun428 @mariajgrimaldi, we should move this issue to https://github.com/overhangio/tutor-indigo/ repository, so the indigo theme maintainer will address and take decision about theme redesign

**Comment by GlugovGrGlib** [comment]
The new issue was created in the tutor-indigo repository: https://github.com/overhangio/tutor-indigo/issues/83

**Comment by crathbun428** [comment]
@GlugovGrGlib - Thank you! This makes sense to me. My plan is to figure out if there is an appropriate product contact I can chat with about this issue, too. Thank you for creating this issue in the indigo theme repository.

**Comment by GlugovGrGlib** [comment]
@crathbun428 Good news! Edly just resolved this issue today - https://github.com/overhangio/tutor-indigo/issues/83
You can already see the results on the redwood sandbox environment - https://redwood.demo.edly.io/

<img width="1790" alt="Screenshot 2024-06-10 at 19 30 53" src="https://github.com/openedx/frontend-app-learning/assets/22370912/ec137c53-28d7-46fb-91a8-e4d800c1931a">

**Comment by crathbun428** [comment]
@GlugovGrGlib - Amazing! This is such good news - thank you for the head's up!!

**Comment by GlugovGrGlib** [comment]
Fixed by https://github.com/overhangio/tutor-indigo/pull/85
